# This is a basic workflow to help you get started with Actions

name: runTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # set up corretto to run tests
      - name: Run tests
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' 
          java-version: '21'    

      # builds and runs the tests with maven
      - name: Make Maven Wrapper executable
        run: chmod +x mvnw
        
      - name: Build and Test
        run: ./mvnw clean test
